import {Dimensions, StyleSheet} from 'react-native';

export const {width: screenWidth} = Dimensions.get('window');

export const wineriesMapStyles = StyleSheet.create({
  pageContainer: {
    flex: 1,
    flexDirection: 'column',
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
  map_ios: {
    ...StyleSheet.absoluteFillObject,
    top: 100,
  },
  onLoading: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  goToMyPositionButton: {
    width: 40,
    height: 40,
    position: 'absolute',
    bottom: 20,
    right: 20,
    borderRadius: 30,
    backgroundColor: '#d2d2d2',
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterMyPositionButton: {
    width: 40,
    height: 40,
    position: 'absolute',
    bottom: 20,
    right: 65,
    borderRadius: 30,
    backgroundColor: '#d2d2d2',
    alignItems: 'center',
    justifyContent: 'center',
  },
  reloadButton: {
    width: 40,
    height: 40,
    position: 'absolute',
    top: 70,
    right: 20,
    borderRadius: 30,
    backgroundColor: '#d2d2d2',
    alignItems: 'center',
    justifyContent: 'center',
  },
  reloadButton_ios: {
    width: 40,
    height: 40,
    position: 'absolute',
    top: 120,
    right: 20,
    borderRadius: 30,
    backgroundColor: '#d2d2d2',
    alignItems: 'center',
    justifyContent: 'center',
  },
  mapSwitch: {
    position: 'absolute',
    top: 80,
    right: 110,
  },
  cleanButton: {
    width: 40,
    height: 40,
    position: 'absolute',
    top: 70,
    right: 65,
    borderRadius: 30,
    backgroundColor: '#d2d2d2',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cleanButton_ios: {
    width: 40,
    height: 40,
    position: 'absolute',
    top: 120,
    right: 65,
    borderRadius: 30,
    backgroundColor: '#d2d2d2',
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchButton: {
    width: 40,
    height: 40,
    position: 'absolute',
    bottom: 20,
    right: 110,
    borderRadius: 30,
    backgroundColor: '#d2d2d2',
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchMapText: {
    width: screenWidth - 20 - 155,
    height: 40,
    borderRadius: 15,
    borderColor: 'rgba(150, 150, 150, 1)',
    borderWidth: 2,
    position: 'absolute',
    bottom: 20,
    left: 20,
    backgroundColor: 'rgba(210, 210, 210, 0.8)',
  },
  infoMapsButton: {
    position: 'absolute',
    top: 70,
    left: 20,
  },
  infoMapsButton_ios: {
    position: 'absolute',
    top: 120,
    left: 20,
  },
});
