import {StyleSheet} from 'react-native';
import {markerDefaultGreen} from '../../common/constants';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  logo: {
    height: 135,
    width: 135,
    resizeMode: 'contain',
    marginBottom: 75,
  },
  inputView: {
    backgroundColor: markerDefaultGreen,
    borderRadius: 30,
    width: '70%',
    height: 45,
    marginBottom: 20,
    alignItems: 'center',
  },
  TextInput: {
    color: 'white',
    textAlign: 'center',
    flex: 1,
    //fontFamily: 'Novecentosanswide-Normal',
  },
  forgot_button: {
    height: 35,
    borderRadius: 30,
    width: '70%',
    alignItems: 'center',
    fontFamily: 'Novecentosanswide-Normal',
  },
  loginBtn: {
    width: '80%',
    borderRadius: 25,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 0,
  },
  loginText: {
    color: 'white',
    width: '100%',
    fontSize: 18,
    justifyContent: 'center',
    textAlign: 'center',
    fontFamily: 'Novecentosanswide-Normal',
  },
  linkText: {
    flex: 1,
    textAlign: 'center',
    color: '#2191b0',
    fontFamily: 'Novecentosanswide-Normal',
    fontSize: 12,
  },
  loginBtnSubView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: '100%',
  },
  remember_container: {
    flex: 0,
    alignItems: 'center', 
    justifyContent: 'center',
    flexDirection: 'row',
    width: '100%',
    marginBottom: 20,
    marginStart: 0,
  },
  rememberSwitch: {
    position: 'relative',
    top: 0,
    right: 0,
  },
  rememberSwitch_ios: {
    position: 'relative',
    top: 0,
    right: 0,
    transform:  [{ scaleX: 0.8 }, { scaleY: 0.8 }] ,
    marginRight: 5,
  },
  rememberText: {
    fontSize: 12,
    justifyContent: 'center',
    textAlign: 'center',
    fontFamily: 'Novecentosanswide-Normal',
  },
  page: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: '#FFF',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  scroll_container: {
    flex: 1,
    marginHorizontal: 5,
    width: '100%',
  },
  image_container: {
    flex: 0,
    alignItems: 'center', 
    justifyContent: 'center',
    marginTop: 20,
    marginBottom: 20,
    width: '100%',
  },
  input_container: {
    flex: 1,
    alignItems: 'center', 
    justifyContent: 'center',
    width: '100%',
    marginBottom : 80,
  },
});
