import {StyleSheet} from 'react-native';
import {markerDefaultGreen} from '../../common/constants';

export const styles = StyleSheet.create({
  page: {
    flex: 1,
    alignItems: 'center',
    flexDirection: 'column',
    backgroundColor: '#FFF',
  },
  scroll_container: {
    flex : 1,
    marginHorizontal: 10,
    width: '100%',
  },
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  image: {
    marginBottom: 80,
    height: 280,
    width: 280,
    resizeMode: 'contain',
  },
  inputView: {
    backgroundColor: markerDefaultGreen,
    borderRadius: 30,
    width: '70%',
    height: 45,
    marginBottom: 20,
    alignItems: 'center',
  },
  loginBtn: {
    width: '80%',
    borderRadius: 25,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 0,
  },
  loginText: {
    color: 'white',
    width: '100%',
    fontSize: 18,
    justifyContent: 'center',
    textAlign: 'center',
    alignSelf: 'center',
    fontFamily: 'Novecentosanswide-Normal',
  },
  loginBtnSubView: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    height: '100%',
  },
  loginGoogleBtn: {
    width: '95%',  
    borderRadius: 25,  
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loginGoogleText: {
    color: 'white',
    width: '70%',
    fontSize: 18,
    justifyContent: 'center',
    textAlign: 'center',
    alignSelf: 'center',
    fontFamily: 'Novecentosanswide-Normal',
  },
  loginFbBtn: {
    width: '95%',
    borderRadius: 25,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loginFbText: {
    color: 'white',
    width: '70%',
    fontSize: 18,
    justifyContent: 'center',
    textAlign: 'center',
    alignSelf: 'center',
    fontFamily: 'Novecentosanswide-Normal',
  },
  separatorText: {
    color: 'black',
    width: '100%',
    fontSize: 14,
    justifyContent: 'center',
    textAlign: 'center',
    fontFamily: 'Novecentosanswide-Normal',
    marginTop: 20,
  },
  appleButton: {
    width: '95%',
    borderRadius: 25,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loginAppleText: {
    color: 'white',
    width: '70%',
    fontSize: 18,
    justifyContent: 'center',
    textAlign: 'center',
    alignSelf: 'center',
    fontFamily: 'Novecentosanswide-Normal',
  },
  facebook_logo: {
    height: 32,
    width: 32,
    resizeMode: 'contain',
    paddingLeft: 0,
    paddingRight: 50,
  },
  apple_logo: {
    height: 56,
    width: 56,
    resizeMode: 'contain',
    paddingLeft: 0,
    paddingRight: 0,
  },
  google_logo: {
    height: 52,
    width: 52,
    resizeMode: 'contain',
    paddingLeft: 0,
    paddingRight: 0,
  },
  separatorButton: {
    marginTop: 20,
  },
});
