export const icons = {
  cerca: require('../../assets/icon/cerca.png'),
  hambuger_menu: require('../../assets/icon/hamburger_icon.png'),
  mail: require('../../assets/icon/mail.png'),
  mail_popup: require('../../assets/icon/mail_popup.png'),
  mail_popup_bn: require('../../assets/icon/mail_BN.png'),
  web: require('../../assets/icon/web.png'),
  web_popup: require('../../assets/icon/web_popup.png'),
  web_popup_BN: require('../../assets/icon/web_BN.png'),
  youtube: require('../../assets/icon/you.png'),
  tele: require('../../assets/icon/tele.png'),
  insta: require('../../assets/icon/insta.png'),
  facebook: require('../../assets/icon/facebook.png'),
  wineries_map_big: require('../../assets/icon/wineries_map_big.png'),
  tel_popup: require('../../assets/icon/tel_popup.png'),
  tel_popup_bn: require('../../assets/icon/telefono_BN.png'),
  go_to_popup: require('../../assets/icon/go_to_popup.png'),
  winery_marker: require('../../assets/icon/winery_marker.png'),
  winery_marker_big: require('../../assets/icon/winery_marker_big.png'),
  cantina_b_b: require('../../assets/icon/Cantina_B_B.png'),
  cantina_ristoro: require('../../assets/icon/Cantina_ristoro.png'),
  touch: require('../../assets/icon/touch.png'),
  info_map: require('../../assets/icon/info_map.png'),
  posizione: require('../../assets/icon/posizione.png'),
  clean_maps: require('../../assets/icon/clean_map.png'),
  intorno: require('../../assets/icon/intorno.png'),
  reload: require('../../assets/icon/reload.png'),
  natourwine_popup: require('../../assets/icon/natourwine_popup.png'),
  ingranaggio_piccolo: require('../../assets/icon/ingranaggio_piccolo.png'),
  filtri_piccolo: require('../../assets/icon/filtri_piccolo.png'),
  profilo: require('../../assets/icon/profilo.png'),
  profilo_big: require('../../assets/icon/profilo_big.png'),
  cantine_home: require('../../assets/icon/cantine.png'),
  fiere_home: require('../../assets/icon/fiere.png'),
  ristori_home: require('../../assets/icon/ristori4.png'),
  enoteche_marker: require('../../assets/icon/enoteche_marker.png'),
  enoteche_marker_big: require('../../assets/icon/enoteche_marker_big.png'),
  locali_marker: require('../../assets/icon/locali_marker.png'),
  locali_marker_big: require('../../assets/icon/locali_marker_big.png'),
  fiere_marker: require('../../assets/icon/fiere_marker.png'),
  fiere_marker_big: require('../../assets/icon/fiere_marker_big.png'),
};

export const images = {
  logo_calice: require('../../assets/img/logo_calice.png'),
  login_logo: require('../../assets/img/login_logo.png'),
  apple_logo: require('../../assets/img/apple_logo_square_1x.png'),
  facebook_logo: require('../../assets/img/f_logo_RGB-Blue_58.png'),
  google_logo: require('../../assets/img/btn_google_light_normal_hdpi.9.png'),
};
