export enum MapActionsType {
  CHANGE_MAP_TYPE = 'CHANGE_MAP_TYPE',
  CHANGE_SEARCH_AROUND_ME = 'CHANGE_SEARCH_AROUND_ME',
  CHANGE_SEARCH_AROUND_POINT = 'CHANGE_SEARCH_AROUND_POINT',
  CHANGE_FILTER_REGION = 'CHANGE_FILTER_REGION',
  CHANGE_FILTER_PROVINCE = 'CHANGE_FILTER_PROVINCE',
  CHANGE_BNB_FLAG = 'CHANGE_BNB_FLAG',
  CHANGE_REST_FLAG = 'CHANGE_REST_FLAG',
  RESET_EXTRA_FILTER = 'RESET_EXTRA_FILTER',
}
